name: document_scanner
description: A plugin that creates a native platform view that scans documents, as a flutter widget.
version: 0.1.2
homepage: https://github.com/eliasteeny/flutter_document_scanner

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^1.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  plugin:
    platforms:
      android:
        package: com.example.document_scanner
        pluginClass: DocumentScannerPlugin
      ios:
        pluginClass: DocumentScannerPlugin
    # androidPackage: com.example.document_scanner
    # pluginClass: DocumentScannerPlugin

  
  
  
  
  
  
  
  
  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
